name: chef_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  get_it: ^7.6.2
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/ar.json
    - assets/translations/en.json
